### ISSUE TITLE
Проблема с тегами к приложению

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#10]
### Ссылка на страницу с проблемой
https://toomac.me/viewtopic?t=528

### Описание ошибки
Текст "SYSTEM & UTILITIES AVO BRAVO • 30 ИЮНЯ 2017..." плохо виден, а далее вообще что-странное написано: "./POSTING?MODE=EDITPOST&P=574">ПРАВКА".

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-viewtopic-1552403399756](https://user-images.githubusercontent.com/19418601/54211253-0ea54f80-44f2-11e9-80e5-4bd92992c946.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleed

**Comment by avobravo** [comment]
@Rakleed Отличная работа! Решено.
