### ISSUE TITLE
Проблемы с задним фонов для страниц с приложениями

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#11]
### Ссылка на страницу с проблемой
https://toomac.me/viewtopic?t=528

### Описание ошибки
Задний фон (заблюренная растянутая иконка) некрасиво смотрится.

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-viewtopic-1552403399756](https://user-images.githubusercontent.com/19418601/54211399-4ca27380-44f2-11e9-9833-037b274b4eef.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleed

**Comment by avobravo** [comment]
@Rakleed у вас есть предложения? На данный момент происходит блур+масштабирование постера раздачи.

**Comment by rakleed** [comment]
@avobravo у меня нет идей, но мне нравиться, как на Onvix реализованы обложки в виде заднего фона для сериалов.
<details><summary>Скриншоты</summary>

![got](https://user-images.githubusercontent.com/19418601/54698488-7554e980-4b40-11e9-8b69-cb337b1f8f12.png)
![bb](https://user-images.githubusercontent.com/19418601/54698611-a2a19780-4b40-11e9-9d15-36fc9cb61f23.png)

</details>
