### ISSUE TITLE
"Описание", "Установка" и "Скриншоты" два раза написаны рядом

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#12]
### Ссылка на страницу с проблемой
https://toomac.me/viewtopic?t=528

### Описание ошибки
Повторяется два раза слова "Скриншоты", а иногда ещё может повторять два раза "Описание" или "Установка" (https://toomac.me/viewtopic?t=1340).

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-viewtopic-1552403607219](https://user-images.githubusercontent.com/19418601/54211605-a9059300-44f2-11e9-8d79-5cc9e8adcf7f.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleed

**Comment by avobravo** [comment]
Знакомы, сайт ожидает полного перехода на простое форматирование текста и простые заголовки, вместо спойлеров (открытие контента внутри)
