### ISSUE TITLE
Лишний пробел перед "Messages"

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#13]
### Ссылка на страницу с проблемой
https://toomac.me/viewtopic?t=2824

### Описание ошибки
При нажатии на иконку профиля во всплывающем меню перед словом "Messages" стоит лишний пробел.

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-viewtopic-1552403736054](https://user-images.githubusercontent.com/19418601/54211779-f08c1f00-44f2-11e9-8016-0e6eab1e0c8b.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleed

**Comment by avobravo** [comment]
Решено.
