### ISSUE TITLE
Светлый задний фон при включённой тёмной теме

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#23]
### Ссылка на страницу с проблемой
https://toomac.me/

### Описание ошибки
При включённой тёмной теме при загрузке сайта отображается светлый задний фон.

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-1552405924449](https://user-images.githubusercontent.com/19418601/54214796-f59f9d00-44f7-11e9-86bf-07f77c9b0d5e.png)
![screenshot-toomac-me-1552405959552](https://user-images.githubusercontent.com/19418601/54214835-0223f580-44f8-11e9-972e-bbdce6c692fb.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleed

**Comment by rakleed** [comment]
@avobravo всё ещё есть проблема, хотя уже и не такая явная как раньше.
<details><summary>Видео</summary>

![screencast-toomac me-2019 03 19-21-01-58](https://user-images.githubusercontent.com/19418601/54630380-bab6df80-4a8a-11e9-8226-1cae8bbc7043.gif)

</details>

**Comment by avobravo** [comment]
Опишите подробнее

**Comment by rakleed** [comment]
@avobravo gри включённой тёмной теме при загрузке сайта на 0.2–0.5 секунд отображается светлый задний фон, а только потом появляется тёмный.

**Comment by avobravo** [comment]
Такая проблема на страницах раздач имеется, знаем о ней, на главной странице не можем ее визуализировать

**Comment by rakleed** [comment]
@avobravo вот ещё одно [видео](https://yadi.sk/d/xt0rnOxXf4KX2A) с проблемой.
