### ISSUE TITLE
При нажатии "Смотреть видео" и "Выбрать тариф" ничего не происходит

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#4]
### Ссылка на страницу с проблемой

https://toomac.me/io/language/ru/

### Описание ошибки

При нажатии "Смотреть видео" и "Выбрать тариф" перекидывает вверх страницы, вместо открытия нужных сайтов

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-io-language-ru-1552224682017](https://user-images.githubusercontent.com/19418601/54085722-04e4e600-4352-11e9-8cd3-d0a97db673f7.png)
![screenshot-toomac-me-io-language-ru-1552224699078](https://user-images.githubusercontent.com/19418601/54085713-fe566e80-4351-11e9-8200-51aed1261dca.png)

</details>

### Используемый браузер

Google Chrome 72.0.3626.121

### Никнейм на сайте

Rakleed

**Comment by avobravo** [comment]
Видео (в 3 экземплярах) еще не готово, процессинг для ежемесячной оплаты так-же
