### ISSUE TITLE
Иконки соцсетей очень маленькие

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#5]
### Ссылка на страницу с проблемой

https://toomac.me/io/

### Описание ошибки

Иконки соцсетей в самом низу страницы очень маленькие

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-io-language-ru-1552224881457](https://user-images.githubusercontent.com/19418601/54085767-93596780-4352-11e9-9f1a-d38f87912c62.png)

</details>

### Используемый браузер

Google Chrome 72.0.3626.121

### Никнейм на сайте

Rakleed

**Comment by avobravo** [comment]
Так задумано дизайнером, внутри сайта иконки больше

**Comment by rakleed** [comment]
@avobravo просто из-за того, что они очень маленькие, их сложно заметить и нажать на нужную иконку с первого раза.
