### ISSUE TITLE
Шрифт фразы "Simplicity is our passion." слишком большой

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#6]
### Ссылка на страницу с проблемой
https://toomac.me/viewtopic?t=2237

### Описание ошибки
Шрифт текста "Simplicity is our passion." в самом низу страницы намного больше, чем "© 2017-2019 Toomac Inc."

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-viewtopic-1552225227303](https://user-images.githubusercontent.com/19418601/54085829-5f327680-4353-11e9-8b5d-dbaed08a6e54.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleed

**Comment by avobravo** [comment]
Решено
