### ISSUE TITLE
При нажатии на сменяющееся изображение ничего не происходит

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#7]
### Ссылка на страницу с проблемой
https://toomac.me

### Описание ошибки
При нажатии на сменяющееся изображение в верхней части ничего не происходит. Кроме карточки с "Twitterrific 5", но при этом открывается тема с "macOS Mojave 10.14.1 (18B75) [MAS]"

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-1552225561220](https://user-images.githubusercontent.com/19418601/54085901-2b0b8580-4354-11e9-9eed-56ae833d437b.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleedoomac-me-1552225561220](https://user-images.githubusercontent.com/19418601/54085885-00b9c800-4354-11e9-9b8b-a6b5e7447c80.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleed

**Comment by avobravo** [comment]
Решено
