### ISSUE TITLE
При нажатии на изображения под заголовком "Write More" ничего не происходит

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#8]
### Ссылка на страницу с проблемой
https://toomac.me

### Описание ошибки
При нажатии на изображения под заголовком "Write More" ничего не происходит, а при нажатии на ссылку "See all" напротив "Write More" просто перезагружается страница.

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-1552226365259](https://user-images.githubusercontent.com/19418601/54086015-d9fc9100-4355-11e9-9636-504878077b46.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleed

**Comment by avobravo** [comment]
Решено

**Comment by rakleed** [comment]
@avobravo при нажатии на карточки под заголовком "Write More" всё равно ничего не происходит.

**Comment by avobravo** [comment]
Сами статьи на данный момент муляж
