### ISSUE TITLE
При нажатии на категорию приложения открывается описание приложения

### ISSUE THREAD

**Issue by rakleed** [toomac-me/update-2.0#9]
### Ссылка на страницу с проблемой
https://toomac.me

### Описание ошибки
При нажатии на категорию любого приложения перекидывает на страницу с приложением, а не в раздел сайта для этой категории.

<details><summary>Скриншот(ы)</summary>

![screenshot-toomac-me-1552226620971](https://user-images.githubusercontent.com/19418601/54086064-72931100-4356-11e9-802c-2c2d8ddd57d7.png)

</details>

### Используемый браузер
Google Chrome 72.0.3626.121

### Никнейм на сайте
Rakleed

**Comment by avobravo** [comment]
@Rakleed Данные категории несут информативный характер, как и в Mac Appstore, по этой причине в большинстве случаев есть кнопки "See more".
Закрыто.
